#!/usr/bin/env node
var s3 = require('aws2js').load('s3');
var fs = require('fs');
var path = require('path');

if (process.argv.length < 4) {
    console.log(process.argv[1], "bucketPath file");
    process.exit(0);
}

var bucket = process.argv[2].split("/")[0];
var dir = process.argv[2].split("/").slice(1).join("/");
var file = process.argv[3];

s3.setCredentials(process.env.AWS_ACCESS_KEY_ID, process.env.AWS_SECRET_ACCESS_KEY);
s3.setBucket(bucket);

// Update index.html with new version
if (dir == "index.html") {
    var index = "";
    s3.get(dir, 'stream', function (err, res) {
       if (err) console.log(err);

       res.on('data', function(buf) {
          index += buf.toString(); 
       });

       res.on('end', function() {
          // file must contain new version, replace for all platforms
          index = index.replace(/ElasticWolf-(osx|win|linux)-[0-9\.]+zip/g, 'ElasticWolf-$1-' + file + '.zip');
          index = index.replace(/ElasticWolf-[0-9\.]+xpi/g, 'ElasticWolf-' + file + '.xpi');
          index = index.replace(/ElasticWolf version [0-9\.]+/g, 'ElasticWolf version ' + file);

          // Upload modified index to back into S3 bucket 
          s3.putBuffer(dir, new Buffer(index), 'public-read', {'content-type':'text/html'}, function (err, res) {
             if (err) console.log(err);
             process.exit(0);
          });
       })
    });

} else {
    // Upload file into S3 bucket
    var type = 'application/zip';
    switch (path.extname(file)) {
    case '.xpi': 
        type = "application/x-xpinstall";
        break;
    case ".html":
    case ".htm":
        type = "text/html";
        break;
    }
    s3.putFile(dir, file, 'public-read', {'content-type':type}, function (err, res) {
       if (err) console.log(err);
       process.exit(0);
    });
}

