#!/bin/sh

xulrunner=$(which xulrunner)
if [ "$xulrunner" = "" ]; then
   echo "Please install xullrunner"
   echo 
   echo "If xulrunner package is not availbale, please, use the following commands below:"
   echo
   echo 'cd /opt'
   echo 'sudo wget -O- https://ftp.mozilla.org/pub/mozilla.org/xulrunner/releases/13.0/runtimes/xulrunner-13.0.en-US.linux-`uname -p`.tar.bz2 | tar -xj'
   echo 'sudo ln -s /opt/xulrunner/xulrunner /usr/bin/xulrunner'
   exit
fi

exec $xulrunner -app $(dirname $0)/application.ini

