#!/bin/sh
if command -v emerge 2>&1 >/dev/null; then
   xulrunner="palemoon"
else
   xulrunner=$(which xulrunner)
fi
if [ "$xulrunner" = "" ]; then
   echo "Please install xulrunner"
   echo
   echo "If xulrunner package is not available, please use the following commands:"
   echo
   echo 'cd /opt'
   echo 'sudo wget -O- https://ftp.mozilla.org/pub/mozilla.org/xulrunner/releases/13.0/runtimes/xulrunner-13.0.en-US.linux-`uname -p`.tar.bz2 | tar -xj'
   echo 'sudo ln -s /opt/xulrunner/xulrunner /usr/bin/xulrunner'
   exit
fi

exec $xulrunner -app $(dirname $0)/application.ini

